total_sources: 8
sources:
  nist-cswp-29:
    title: The NIST Cybersecurity Framework (CSF) 2.0
    resource: https://doi.org/10.6028/NIST.CSWP.29
    author: National Institute of Standards and Technology (NIST)
    last_modified: '2024-02-26T00:00:00Z'
    used_by:
    - crosswalks/eu-cra/eu-cra-mapping
    - crosswalks/eu-nis2/eu-nis2-mapping
    - crosswalks/iec-62443/iec-62443-mapping
    - crosswalks/iso-iec-27001/iso-iec-27001-mapping
    - framework/categories/de-ae
    - framework/categories/de-cm
    - framework/categories/gv-oc
    - framework/categories/gv-ov
    - framework/categories/gv-po
    - framework/categories/gv-rm
    - framework/categories/gv-rr
    - framework/categories/gv-sc
    - framework/categories/id-am
    - framework/categories/id-im
    - framework/categories/id-ra
    - framework/categories/pr-aa
    - framework/categories/pr-at
    - framework/categories/pr-ds
    - framework/categories/pr-ir
    - framework/categories/pr-ps
    - framework/categories/rc-co
    - framework/categories/rc-rp
    - framework/categories/rs-an
    - framework/categories/rs-co
    - framework/categories/rs-ma
    - framework/categories/rs-mi
    - framework/functions/detect
    - framework/functions/govern
    - framework/functions/identify
    - framework/functions/protect
    - framework/functions/recover
    - framework/functions/respond
    - framework/subcategories/de-ae-02
    - framework/subcategories/de-ae-03
    - framework/subcategories/de-ae-04
    - framework/subcategories/de-ae-06
    - framework/subcategories/de-ae-07
    - framework/subcategories/de-ae-08
    - framework/subcategories/de-cm-01
    - framework/subcategories/de-cm-02
    - framework/subcategories/de-cm-03
    - framework/subcategories/de-cm-06
    - framework/subcategories/de-cm-09
    - framework/subcategories/gv-oc-01
    - framework/subcategories/gv-oc-02
    - framework/subcategories/gv-oc-03
    - framework/subcategories/gv-oc-04
    - framework/subcategories/gv-oc-05
    - framework/subcategories/gv-ov-01
    - framework/subcategories/gv-ov-02
    - framework/subcategories/gv-ov-03
    - framework/subcategories/gv-po-01
    - framework/subcategories/gv-po-02
    - framework/subcategories/gv-rm-01
    - framework/subcategories/gv-rm-02
    - framework/subcategories/gv-rm-03
    - framework/subcategories/gv-rm-04
    - framework/subcategories/gv-rm-05
    - framework/subcategories/gv-rm-06
    - framework/subcategories/gv-rm-07
    - framework/subcategories/gv-rr-01
    - framework/subcategories/gv-rr-02
    - framework/subcategories/gv-rr-03
    - framework/subcategories/gv-rr-04
    - framework/subcategories/gv-sc-01
    - framework/subcategories/gv-sc-02
    - framework/subcategories/gv-sc-03
    - framework/subcategories/gv-sc-04
    - framework/subcategories/gv-sc-05
    - framework/subcategories/gv-sc-06
    - framework/subcategories/gv-sc-07
    - framework/subcategories/gv-sc-08
    - framework/subcategories/gv-sc-09
    - framework/subcategories/gv-sc-10
    - framework/subcategories/id-am-01
    - framework/subcategories/id-am-02
    - framework/subcategories/id-am-03
    - framework/subcategories/id-am-04
    - framework/subcategories/id-am-05
    - framework/subcategories/id-am-07
    - framework/subcategories/id-am-08
    - framework/subcategories/id-im-01
    - framework/subcategories/id-im-02
    - framework/subcategories/id-im-03
    - framework/subcategories/id-im-04
    - framework/subcategories/id-ra-01
    - framework/subcategories/id-ra-02
    - framework/subcategories/id-ra-03
    - framework/subcategories/id-ra-04
    - framework/subcategories/id-ra-05
    - framework/subcategories/id-ra-06
    - framework/subcategories/id-ra-07
    - framework/subcategories/id-ra-08
    - framework/subcategories/id-ra-09
    - framework/subcategories/id-ra-10
    - framework/subcategories/pr-aa-01
    - framework/subcategories/pr-aa-02
    - framework/subcategories/pr-aa-03
    - framework/subcategories/pr-aa-04
    - framework/subcategories/pr-aa-05
    - framework/subcategories/pr-aa-06
    - framework/subcategories/pr-at-01
    - framework/subcategories/pr-at-02
    - framework/subcategories/pr-ds-01
    - framework/subcategories/pr-ds-02
    - framework/subcategories/pr-ds-10
    - framework/subcategories/pr-ds-11
    - framework/subcategories/pr-ir-01
    - framework/subcategories/pr-ir-02
    - framework/subcategories/pr-ir-03
    - framework/subcategories/pr-ir-04
    - framework/subcategories/pr-ps-01
    - framework/subcategories/pr-ps-02
    - framework/subcategories/pr-ps-03
    - framework/subcategories/pr-ps-04
    - framework/subcategories/pr-ps-05
    - framework/subcategories/pr-ps-06
    - framework/subcategories/rc-co-03
    - framework/subcategories/rc-co-04
    - framework/subcategories/rc-rp-01
    - framework/subcategories/rc-rp-02
    - framework/subcategories/rc-rp-03
    - framework/subcategories/rc-rp-04
    - framework/subcategories/rc-rp-05
    - framework/subcategories/rc-rp-06
    - framework/subcategories/rs-an-03
    - framework/subcategories/rs-an-06
    - framework/subcategories/rs-an-07
    - framework/subcategories/rs-an-08
    - framework/subcategories/rs-co-02
    - framework/subcategories/rs-co-03
    - framework/subcategories/rs-ma-01
    - framework/subcategories/rs-ma-02
    - framework/subcategories/rs-ma-03
    - framework/subcategories/rs-ma-04
    - framework/subcategories/rs-ma-05
    - framework/subcategories/rs-mi-01
    - framework/subcategories/rs-mi-02
    - glossary/community-profile
    - glossary/csf-category
    - glossary/csf-core
    - glossary/csf-subcategory
    - glossary/csf-tier
    - glossary/informative-reference
    - glossary/organizational-profile
    - guidance/implementation-examples/csf-implementation-examples-guide
    - guidance/quick-start-guides/community-profiles-guide
    - guidance/quick-start-guides/creating-and-using-organizational-profiles
    - guidance/quick-start-guides/cybersecurity-supply-chain-risk-management
    - guidance/quick-start-guides/enterprise-risk-management-quick-start
    - guidance/quick-start-guides/erm-and-workforce-quick-start
    - guidance/quick-start-guides/informative-references-quick-start
    - guidance/quick-start-guides/resource-and-overview-guide
    - guidance/quick-start-guides/small-business-quick-start
    - guidance/quick-start-guides/using-ai-for-csf-quick-start
    - guidance/quick-start-guides/using-csf-tiers
    - guidance/tools/cprt-and-reference-tool
    - informative-references/cis-controls-v8
    - informative-references/csf-1-1-reference
    - informative-references/iso-iec-27001-2022
    - informative-references/olir-program
    - informative-references/sp-800-221a
    - informative-references/sp-800-53-r5
    - profiles/community/community-profiles-development
    - profiles/organizational/creating-organizational-profiles
    - profiles/organizational/current-state-profile
    - profiles/organizational/profile-template
    - profiles/organizational/target-state-profile
    - profiles/tiers/tier-1-partial
    - profiles/tiers/tier-2-risk-informed
    - profiles/tiers/tier-3-repeatable
    - profiles/tiers/tier-4-adaptive
    - timeline/csf-2-0-publication
  nist-cprt-csf-2-0:
    title: "NIST Cybersecurity and Privacy Reference Tool (CPRT) \u2014 CSF 2.0 Implementation\
      \ Examples"
    resource: https://csrc.nist.gov/projects/cprt
    author: National Institute of Standards and Technology (NIST)
    last_modified: '2024-02-26T00:00:00Z'
    used_by: []
  nist-ir-8477:
    title: 'NIST IR 8477: Mapping Cybersecurity and Privacy Concepts Using the National
      Online Informative References (OLIR) Program'
    resource: https://doi.org/10.6028/NIST.IR.8477
    author: National Institute of Standards and Technology (NIST)
    last_modified: '2023-07-28T00:00:00Z'
    used_by:
    - crosswalks/eu-cra/eu-cra-mapping
    - crosswalks/eu-nis2/eu-nis2-mapping
    - crosswalks/iec-62443/iec-62443-mapping
    - crosswalks/iso-iec-27001/iso-iec-27001-mapping
    - informative-references/csf-1-1-reference
    - informative-references/olir-program
    - informative-references/sp-800-221a
  nist-cswp-6:
    title: Framework for Improving Critical Infrastructure Cybersecurity, Version
      1.1
    resource: https://doi.org/10.6028/NIST.CSWP.6
    author: National Institute of Standards and Technology (NIST)
    last_modified: '2018-04-16T00:00:00Z'
    used_by:
    - timeline/csf-1-1-publication
  nist-ir-8286:
    title: 'NIST IR 8286: Integrating Cybersecurity and Enterprise Risk Management
      (ERM)'
    resource: https://doi.org/10.6028/NIST.IR.8286
    author: National Institute of Standards and Technology (NIST)
    last_modified: '2020-10-15T00:00:00Z'
    used_by:
    - glossary/cybersecurity-risk
  nist-ir-8406:
    title: Community Profile for Cybersecurity in Genomic Data
    resource: https://doi.org/10.6028/NIST.IR.8406
    author: National Institute of Standards and Technology (NIST)
    last_modified: '2022-09-01T00:00:00Z'
    used_by: []
  nist-ir-8441:
    title: Cybersecurity Profile for the Hybrid Satellite Network
    resource: https://doi.org/10.6028/NIST.IR.8441
    author: National Institute of Standards and Technology (NIST)
    last_modified: '2023-05-01T00:00:00Z'
    used_by: []
  eo-13636:
    title: 'Executive Order 13636: Improving Critical Infrastructure Cybersecurity'
    resource: https://www.federalregister.gov/documents/2013/02/19/2013-03725/improving-critical-infrastructure-cybersecurity
    author: Executive Office of the President
    last_modified: '2013-02-12T00:00:00Z'
    used_by:
    - timeline/csf-1-0-publication
    - timeline/eo-13636
